version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 443:443
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl:ro
      - ./.htpsswd:/etc/nginx/.htpsswd
    networks:
      shared-internal-network:
        - name: home-server-internal-network
        - external: true

volumes:
  prometheus-data:

networks:
  internal-network:
    driver: bridge
