version: '3.8'

services:
  nginx:
    image: nginx
    volumes:
      - ./conf.d:/etc/nginx/conf.d
      - ./nginx.conf:/etc/nginx/nginx.conf
    deploy:
      replicas: 2
    ports:
      - 80:80
      - 443:443
    networks:
      - home_server_internal_network

networks:
  home_server_internal_network:
    external: true
