name: Build

on:
  push:
    branches:
      - "master"
    paths: ["docs/**"]

jobs:
  deploy:
    environment: Production
    timeout-minutes: 15
    runs-on: ubuntu-latest
    env:
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: User Node.js LTS
        uses: actions/setup-node@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2.2.4
        with:
          run_install: false

      - name: Install Vercel CLI
        run: pnpm -g add vercel@canary

      - name: Install Dependencies
        run: cd docs && pnpm install --frozen-lockfile

      - name: Build
        run: cd docs && pnpm run build

      - name: Trigger Production Deployment
        run: cd docs && vercel deploy -y --prod --token=${{ secrets.VERCEL_TOKEN }} > deployment-url.txt

      - name: Deployment Failure Alert
        if: ${{ failure() }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: "🚨🚨🚨 MASTER BRANCH DOCUMENTATION DEPLOYMENT FAILED 🚨🚨🚨"
          embed-description: " .<@517983211708612609> deploy job on master branch failed, check [HERE](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})"

      - name: Deployment Failure Alert
        if: ${{ success() }}
        uses: tsickert/discord-webhook@v5.3.0
        with:
          webhook-url: ${{ secrets.DISCORD_WEBHOOK_URL }}
          embed-title: "🟢 NEW VERSION OF DOCUMENTATION DEPLOYED"
          embed-description: "Documentation deployed success!"
