name: Ping Server

on:
  workflow_dispatch: {}

jobs:
  ping-server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: ping-server
        run: ping ${{ secrets.SERVER_IP_ADDRESS }}

      - name: Host Down Alert
        uses: rjstone/discord-webhook-notify@v1
        if: ${{ failure() }}
        with:
          severity: warn
          details: Test Cancelled!
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
